using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Toolsets.Input.Editor
{
    [CustomEditor(typeof(InputManager))]
    public class InputManagerEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Input Generation", EditorStyles.boldLabel);

            if (GUILayout.Button("Generate Clean Inputs", GUILayout.Height(40)))
            {
                GenerateCleanInputs();
            }

            EditorGUILayout.HelpBox("Generates strongly-typed access to all inputs.\nYou get the wrapper types (InputButton, InputFloatValue, etc.).", MessageType.Info);
        }

        private void GenerateCleanInputs()
        {
            var inputManager = (InputManager)target;

            if (inputManager.inputActions == null)
            {
                EditorUtility.DisplayDialog("Input Generator", "Please assign an InputActionAsset first.", "OK");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated. Do not edit manually.");
            sb.AppendLine("// Generated on: " + System.DateTime.Now);
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Toolsets.Input;");
            sb.AppendLine();
            sb.AppendLine("public static class Inputs");
            sb.AppendLine("{");
            sb.AppendLine("    private static InputManager Instance => InputManager.Instance;");
            sb.AppendLine();

            sb.AppendLine("    #region Buttons");
            foreach (var button in inputManager.buttons)
            {
                if (button.reference?.action == null) continue;
                var name = CleanName(button.reference.action.name);
                sb.AppendLine($"    public static InputButton {name} => Instance.GetButton(\"{button.reference.action.name}\");");
            }
            sb.AppendLine("    #endregion");
            sb.AppendLine();

            sb.AppendLine("    #region Float Values");
            foreach (var val in inputManager.floatValues)
            {
                if (val.reference?.action == null) continue;
                var name = CleanName(val.reference.action.name);
                sb.AppendLine($"    public static InputFloat {name} => Instance.GetFloat(\"{val.reference.action.name}\");");
            }
            sb.AppendLine("    #endregion");
            sb.AppendLine();

            sb.AppendLine("    #region Vector2 Values");
            foreach (var val in inputManager.vector2Values)
            {
                if (val.reference?.action == null) continue;
                var name = CleanName(val.reference.action.name);
                sb.AppendLine($"    public static InputVector2 {name} => Instance.GetVector2(\"{val.reference.action.name}\");");
            }
            sb.AppendLine("    #endregion");

            sb.AppendLine("}");

            var path = "Assets/Scripts/AutoGenerated/Inputs.cs";
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, sb.ToString());

            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("Success!", $"Inputs class generated at:\n{path}", "OK");
        }

        private static string CleanName(string name)
        {
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result) || char.IsDigit(result[0]))
                result = "_" + result;

            return ObjectNames.NicifyVariableName(result).Replace(" ", "");
        }
    }
}
